spring:
  application:
    name: gateway-service

server:
  port: 8080

services:
  auth:
    base-url: ${SERVICES_AUTH_BASE_URL:http://localhost:8081}
  project:
    base-url: ${SERVICES_PROJECT_BASE_URL:http://localhost:8082}
  analytics:
    base-url: ${SERVICES_ANALYTI:http://localhost:8083}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
info:
  app:
    name: gateway-service
    version: 0.0.1-SNAPSHOT
    description: Taskboard gateway microservice backend