spring:
  application:
    name: project-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/taskboard}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

services:
  auth:
    base-url: ${SPRING-AUTH-URI:http://localhost:8081}

server:
  port: 8082

security:
  jwt:
    secret: c3VwZXItc2VjcmV0LWtleS10aGF0LWlzLWF0LWxlYXN0LTMyLWJ5dGVz
    expiration-seconds: 3600

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
info:
  app:
    name: project-service
    version: 0.0.1-SNAPSHOT
    description: Taskboard project microservice backend