spring:
    application:
        name: auth-service
    data:
      mongodb:
          uri: mongodb://localhost:27017/taskboard-auth

server:
    port: 8081

security:
    jwt:
        secret: c3VwZXItc2VjcmV0LWtleS10aGF0LWlzLWF0LWxlYXN0LTMyLWJ5dGVz
        expiration-seconds: 3600
